language: php

php: [7.0, 7.1, 7.2]

cache:
  directories:
    - vendor

before_script:
  - composer install --prefer-dist --dev

script:
    - vendor/bin/phpspec run -fpretty
    - bin/funk functional
